spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      CharSet: utf-8
      characterEncoding: utf-8
      useUnicode: true
      connection:
        CharSet: utf-8
        characterEncoding: utf-8
        useUnicode: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    tomcat:
      connection-properties:
        useUnicode: true
        characterEncoding: utf-8
    url: jdbc:postgresql://localhost:5432/library?useUnicode=true&characterEncoding=utf8
    useUnicode: true
    username: postgres
    password: 1
    encoding: UTF-8
    charSet: UTF-8